# Generated by Django 5.1.3 on 2024-11-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tid', models.CharField(max_length=255)),
                ('Tname', models.CharField(max_length=255)),
                ('Temail', models.EmailField(max_length=255)),
                ('Tcontact', models.CharField(max_length=255)),
                ('Tsubject', models.CharField(max_length=255)),
                ('Tdeleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
