# Generated by Django 5.1.3 on 2024-11-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Tdeleted',
            field=models.BooleanField(default=False),
        ),
    ]
