# Generated by Django 5.1.3 on 2024-11-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('semail', models.EmailField(max_length=100)),
                ('scontact', models.CharField(max_length=50)),
                ('sdelete', models.BooleanField(default=False)),
            ],
        ),
    ]
